site_name: SceneShift
site_url: https://tandukuda.github.io/SceneShift/
repo_url: https://github.com/tandukuda/SceneShift
repo_name: tandukuda/SceneShift

theme:
  name: terminal
  features:
    - navigation.sections # Groups items in sidebar
    - content.code.copy # Adds copy button to code blocks
    - navigation.top.search_button.hide
  palette: dark

nav:
  - Home: index.md
  - Getting Started: installation.md
  - Usage: usage.md
  - Safety & Disclaimer: safety.md
  - Troubleshooting: troubleshooting.md
